defmodule Scry2.Uplink.UploadKey do
  @moduledoc """
  Stable, content-addressed identity for a domain event on the wire
  (client/server split, ADR-042 Phase 2).

  The key must be identical before and after a client **retranslation** so
  that re-uploads upsert (not duplicate) on the server:

    * Raw-derived events (`mtga_source_id` present) key on
      `(mtga_source_id, event_type, sequence)` — retranslation never deletes
      raw, so these are stable. The local `id` is deliberately excluded (it is
      regenerated by a rebuild).
    * Synthetic events (`mtga_source_id` nil) key on their local `id` —
      retranslation preserves synthetic events untouched, so their id is stable.
  """

  alias Scry2.Events.EventRecord

  @spec derive(EventRecord.t()) :: String.t()
  def derive(%EventRecord{mtga_source_id: source, event_type: type, sequence: sequence})
      when is_integer(source) do
    "r:#{source}:#{type}:#{sequence}"
  end

  def derive(%EventRecord{mtga_source_id: nil, id: id, event_type: type}) when is_integer(id) do
    "s:#{id}:#{type}"
  end
end
