import Config

# SERVER tier (client/server split, ADR-042 Phase 2) — Postgres, dev only.
# The client is SQLite-only and does not need this; start it with
# `docker compose up -d` when developing the server.
config :scry_2, Scry2.ServerRepo,
  hostname: "localhost",
  port: 5433,
  username: "scry2",
  password: "scry2",
  database: "scry2_server_dev",
  pool_size: 5

# Configure your database
#
# Dev *is* the local instance. `scripts/install-dev` runs this
# configuration as the user's everyday app — port 6015, the real
# database — and a bare `mix phx.server` is the same thing. There is no
# second, throwaway dev database. Only ever run one process against it:
# SQLite tolerates one writer. See DEVELOPMENT.md.
#
# The path spells out `Scry2.Platform.data_dir/0`'s Linux branch rather
# than calling it: Mix evaluates config before compiling, so config files
# cannot reach into the application. Keep the two in step.
config :scry_2, Scry2.Repo,
  database: Path.expand("~/.local/share/scry_2/scry_2.db"),
  pool_size: 5,
  journal_mode: :wal,
  busy_timeout: 30_000,
  default_transaction_mode: :immediate,
  custom_pragmas: [
    # Safe with WAL mode — fsync only on checkpoint, not every commit. 2-3x faster writes.
    synchronous: :normal,
    # 128MB memory-mapped I/O — major read speedup, reduces time spent holding locks.
    mmap_size: 134_217_728,
    # Cap WAL file at 64MB — prevents unbounded growth during heavy ingestion.
    journal_size_limit: 67_108_864,
    # Keep temp tables in RAM.
    temp_store: 2
  ],
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :scry_2, Scry2Web.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Port 6015 — the local instance's port, and the only one Scry2 serves.
  http: [ip: {127, 0, 0, 1}, port: 6015],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "5+GhXhTjxNK/szAkqvhUGvpnM708Ed2hv0AdvoKgtk5BcJOHCQISBqxZtQ8myFQZ",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:scry_2, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:scry_2, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :scry_2, Scry2Web.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/scry_2_web/router\.ex$",
      ~r"lib/scry_2_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :scry_2, dev_routes: true

# Use the component-aware formatter so thinking logs show [level][component].
# The formatter is also used for stdout output; the in-browser Console drawer
# has its own `Scry2.Console.CaptureLogOutput` that parses component metadata separately.
config :logger, :default_formatter,
  format: {Scry2.Log.FormatForStdout, :format},
  metadata: [:component]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# ex_code_view output directory (dev tool — see `mix view --help`)
config :ex_code_view, output_dir: "tmp"

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
