defmodule Scry2.MtgaLogIngestion.GitHubIssueReport do
  @moduledoc """
  Pure builder that turns a list of error records into a pre-filled
  GitHub "new issue" form: a deterministic title that groups identical
  reports across users, a markdown body with payload samples, and the
  full URL the browser should open.

  ## Determinism / dedup

  The title is derived from the **error signature** — `(event_type,
  category)` — not from per-record fields like ID or timestamp. Two
  users hitting the same broken MTGA update produce identical titles,
  so the maintainer can collapse duplicates by sorting the issue list
  on title.

  When several distinct signatures are reported in one batch, the
  title names the dominant signature plus an "+N other(s)" suffix —
  still stable across users with the same mix.

  ## URL length

  GitHub's `?body=` query parameter has no documented hard cap, but
  some browsers and proxies truncate around 8 KB. The builder keeps
  the body well under that:

    * Per signature: up to `@samples_per_signature` raw payloads.
    * Per payload: truncated at `@payload_truncate_bytes` characters,
      with a clear `... (truncated)` marker.

  Anything that doesn't fit is summarised in the body's "summary"
  table, so the maintainer always sees the full count + signature
  breakdown even when individual payloads are dropped.
  """

  @issue_url_base "https://github.com/shawnmccool/scry_2/issues/new"
  @samples_per_signature 2
  @payload_truncate_bytes 1_500
  @body_max_bytes 6_000

  @type signature :: {event_type :: String.t(), category :: atom()}

  @type build_result :: %{
          title: String.t(),
          body: String.t(),
          url: String.t(),
          signatures: [%{signature: signature(), count: non_neg_integer()}]
        }

  @doc """
  Build the issue title, markdown body, and pre-filled GitHub URL.

  Inputs are taken as a value to keep the function pure: pass the
  result of `Scry2.MtgaLogIngestion.export_errors/0` (or a stub).
  """
  @spec build(map(), keyword()) :: build_result()
  def build(%{errors: errors} = export, opts \\ []) when is_list(errors) do
    platform = Keyword.get(opts, :platform, platform_string())
    version = Map.get(export, :scry2_version) || Keyword.get(opts, :version, "unknown")

    grouped = group_by_signature(errors)
    title = build_title(grouped)
    body = build_body(version, platform, length(errors), grouped)
    url = build_url(title, body)

    %{
      title: title,
      body: body,
      url: url,
      signatures:
        Enum.map(grouped, fn {sig, records} -> %{signature: sig, count: length(records)} end)
    }
  end

  @doc """
  Categorise an error message into a signature tag — same buckets as
  `Scry2.MtgaLogIngestion.user_friendly_error/1`. Pure.
  """
  @spec categorize(String.t() | nil) :: :decode_failure | :missing_field | :generic | :unknown
  def categorize(nil), do: :unknown

  def categorize(message) when is_binary(message) do
    cond do
      String.contains?(message, "failed to decode") -> :decode_failure
      String.contains?(message, ["key :", "enforce_keys", "missing required"]) -> :missing_field
      true -> :generic
    end
  end

  # ── Internals ─────────────────────────────────────────────────────────

  defp group_by_signature(errors) do
    errors
    |> Enum.group_by(fn err ->
      {Map.get(err, :event_type, "unknown"), categorize(Map.get(err, :error_summary))}
    end)
    |> Enum.sort_by(fn {_sig, records} -> -length(records) end)
  end

  defp build_title([]) do
    "[ingestion error] no records provided"
  end

  defp build_title(grouped) do
    {{event_type, category}, _records} = hd(grouped)
    others = length(grouped) - 1

    base = "[ingestion error] #{event_type} — #{category_label(category)}"

    case others do
      0 -> base
      1 -> "#{base} (+1 other type)"
      n -> "#{base} (+#{n} other types)"
    end
  end

  defp category_label(:decode_failure), do: "failed to decode payload"
  defp category_label(:missing_field), do: "missing required field"
  defp category_label(:generic), do: "unexpected error"
  defp category_label(:unknown), do: "unclassified error"

  defp build_body(version, platform, total_count, grouped) do
    signature_table = build_signature_table(grouped, total_count)
    samples = build_samples(grouped)

    """
    ## Environment
    - **Scry2 version:** `#{version}`
    - **Platform:** `#{platform}`
    - **Total errors in batch:** #{total_count}

    ## Signature summary
    #{signature_table}

    ## Sample payloads
    Up to #{@samples_per_signature} sample(s) per signature, each truncated to ~#{@payload_truncate_bytes} characters.

    #{samples}

    ---
    *This report was generated by the Scry2 Operations page. The user reviewed the full payload before sending.*
    """
    |> truncate_body()
  end

  defp build_signature_table(grouped, total_count) do
    rows =
      Enum.map_join(grouped, "\n", fn {{event_type, category}, records} ->
        count = length(records)
        pct = if total_count > 0, do: round(count * 100 / total_count), else: 0
        "| `#{event_type}` | `#{category}` | #{count} (#{pct}%) |"
      end)

    """
    | Event type | Category | Count |
    |---|---|---|
    #{rows}
    """
  end

  defp build_samples(grouped) do
    Enum.map_join(grouped, "\n\n", fn {{event_type, category}, records} ->
      sample_records = Enum.take(records, @samples_per_signature)

      """
      ### `#{event_type}` — `#{category}`

      #{Enum.map_join(sample_records, "\n\n", &format_sample/1)}
      """
    end)
  end

  defp format_sample(record) do
    payload =
      record
      |> Map.get(:raw_event, %{})
      |> Jason.encode!(pretty: true)
      |> truncate_payload()

    occurred = Map.get(record, :occurred_at)
    occurred_str = if occurred, do: "**occurred_at:** `#{occurred}`\n", else: ""

    """
    #{occurred_str}**error:** `#{Map.get(record, :error_summary, "")}`

    ```json
    #{payload}
    ```
    """
  end

  defp truncate_payload(text) when byte_size(text) > @payload_truncate_bytes do
    binary_part(text, 0, @payload_truncate_bytes) <> "\n... (truncated)"
  end

  defp truncate_payload(text), do: text

  defp truncate_body(body) when byte_size(body) > @body_max_bytes do
    binary_part(body, 0, @body_max_bytes) <>
      "\n\n... (body truncated for URL length; export the JSON report for the full data)"
  end

  defp truncate_body(body), do: body

  defp build_url(title, body) do
    query =
      URI.encode_query(%{
        "title" => title,
        "body" => body,
        "labels" => "ingestion-error,user-report"
      })

    "#{@issue_url_base}?#{query}"
  end

  defp platform_string do
    {os_family, os_name} = :os.type()
    "#{os_family}-#{os_name}"
  end
end
